---
- name: "Download Hosts file from {{ hosts_url }}"
  get_url:
    url: "{{ hosts_url }}"
    dest: '{{ download_path }}'
  notify: copy hosts file

- name: 'check if {{ tmp_path }} exists'
  stat:
    path: '{{ tmp_path }}'
  register: temp_hosts
  changed_when: not temp_hosts.stat.exists
  notify: copy hosts file

- meta: flush_handlers

- name: Make sure hostname resolves to localhost
  lineinfile:
    path: '{{ tmp_path }}'
    regexp: "^({{ local_ip }} {{ ansible_facts.nodename }})$"
    line: "{{ local_ip }} {{ ansible_facts.nodename }}"
    insertafter: '127.0.0.1 localhost'

- name: "Add other custom_hosts"
  lineinfile:
    path: '{{ tmp_path }}'
    regexp: "( {{ item.host }})$" # Ending with hostname allowing for the IP to be changed
    line: "{{ item.ip }} {{ item.host }}"
    insertafter: '{{ insert_after_line }}'
  with_items: '{{ custom_hosts }}'
  when: custom_hosts|length

- name: Copy the hosts file to /etc/hosts
  copy:
    src: '{{ tmp_path }}'
    dest: '{{ hosts_file }}'
    mode: 0644
    owner: root
    group: root
    remote_src: yes
    unsafe_writes: '{{ is_docker }}'