---
- name: Converge
  hosts: all
  become: true
  vars:
    recipe: 'fakenews-gambling-porn-social'
    custom_hosts:
      - host: example.com
        ip: 1.1.1.1
      - host: example.test
        ip: 1.2.3.4

  roles:
    - role: hosts_file
