---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: centos-7
    box: centos/7
    memory: 512
    cpus: 1
  - name: centos-8
    box: centos/8
    memory: 512
    cpus: 1
  - name: ubuntu-2004
    box: generic/ubuntu2004
    memory: 512
    cpus: 1
  - name: ubuntu-1804
    box: generic/ubuntu1804
    memory: 512
    cpus: 1
  - name: jessie64
    box: debian/jessie64
    memory: 512
    cpus: 1
  - name: buster64
    box: debian/buster64
    memory: 512
    cpus: 1
  - name: stretch64
    box: debian/stretch64
    memory: 512
    cpus: 1

provisioner:
  name: ansible
verifier:
  name: ansible
