---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Check that the remote config got downloaded
      stat:
        path: /tmp/hosts-template
      register: download_result
      failed_when: 'not download_result.stat.exists'

    - name: Check that the remote config got copied
      stat:
        path: /tmp/hosts
      register: tmp_result
      failed_when: 'not tmp_result.stat.exists'

    - name: "Ensure /etc/hosts contains entry for example.com"
      lineinfile:
        name: /etc/hosts
        line: "1.1.1.1 example.com"
        state: present
      check_mode: true
      register: hosts
      failed_when: (hosts is changed) or (hosts is failed)

    - name: Example assertion
      assert:
        that: download_result.stat.exists
