---
- name: Converge
  hosts: all
  become: true
  vars:
    download_path: /tmp/hosts-template
    tmp_path: /tmp/hosts
    custom_hosts:
      - host: example.com
        ip: 1.1.1.1

  pre_tasks:
    - name: Override slow systemd resolved service on ubuntu libvirt boxes
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf
      when: ansible_distribution == "Ubuntu"

  roles:
    - role: hosts_file
